@DindynApi_HostAddress = http://localhost:5018

GET {{DindynApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{DindynApi_HostAddress}}/auth/login
Content-Type: application/json
{
	"email": "usuario@teste.com",
	"password": "senha123"
}
